import type { Skill } from '../types';

export const skill: Skill = {
    name: 'slack-upload-file',
    title: 'Slack — Upload File',
    summary: 'Upload a file to Slack and optionally share it to a channel or DM.',
    whenToUse:
        'Use when the user wants to upload or share a file in Slack — e.g. attach a report, ' +
        'a CSV export, or an image generated by a previous step.',
    keywords: ['slack', 'upload', 'file', 'attachment', 'image', 'pdf', 'share', 'document'],
    category: 'integration',
    nodeType: 'slack',
    requiresCredential: 'slack',
    body: `
# Slack — Upload File

Uploads a file to Slack and optionally shares it to a channel or DM.

## Required config
- \`credentialId\` (string): Connected Slack credential id.
  Call \`list_credentials({ provider: "slack" })\` to find it.
- \`action\` (string): Must be \`"upload_file"\`.
- \`uploadSource\` (\`"content" | "node"\`):
  - \`"content"\` — text content provided directly via \`fileContent\`.
  - \`"node"\` — base64 file content from an upstream node via \`uploadData\`.
- \`filename\` (string): Filename displayed in Slack (e.g. \`"report.pdf"\`).

## Optional config
- \`fileContent\` (string): Text/expression used when \`uploadSource === "content"\`.
- \`uploadData\` (string): Expression resolving to base64 content (e.g. from a GDrive download node).
- \`uploadMimeType\` (string): MIME type override (auto-detected from \`filename\` when omitted).
- \`shareTarget\` (\`"channel" | "dm" | "none"\`): Where to share after upload. Default \`"none"\`.
- \`channels\` (string): Channel id/name (when \`shareTarget === "channel"\`).
  Call \`list_slack_channels\` and present via \`ask_user\`.
- \`uploadUserId\` (string): User id (when \`shareTarget === "dm"\`).
  Call \`list_slack_users\` and present via \`ask_user\`.

## Output fields
- \`fileId\`: Slack file id
- \`fileName\`: Filename as stored
- \`permalink\`: Public permalink to the file

## Fluxelle workflow
1. Call \`list_credentials({ provider: "slack" })\` → resolve \`credentialId\`.
2. Ask where the file content comes from (typed text vs. upstream node output).
3. Ask whether to share after upload, then resolve channel/user via \`ask_user\`.

## Example — share a CSV to #reports
\`\`\`json
{
  "id": "slack-file-1",
  "type": "slack",
  "name": "Upload CSV to #reports",
  "config": {
    "credentialId": "<resolved-from-list_credentials>",
    "action": "upload_file",
    "uploadSource": "content",
    "filename": "summary.txt",
    "fileContent": "{{ nodes.llm-1.content }}",
    "shareTarget": "channel",
    "channels": "<resolved-from-list_slack_channels>"
  },
  "next": []
}
\`\`\`
`,
};
